[package]
name = "fetch-bug"
version = "0.1.0"
authors = ["AkhIL <akhilman@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {git = "https://github.com/seed-rs/seed.git"}
wasm-bindgen = "0.2.55"
futures = "0.3.4"
